repository_type: pipeline
org_path: local
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-root-tissue-analysis_logo_light.png
    - docs/images/nf-core-root-tissue-analysis_logo_light.png
    - docs/images/nf-core-root-tissue-analysis_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
