name: rootseg
description: Run RootSeg on sequenced reads
keywords:
  - quality control
  - qc
  - adapters
  - fastq
tools:
  - z:
      description: |
        RootSeg gives general quality metrics about your reads.
        It provides information about the quality score distribution
        across your reads, the per base sequence content (%A/C/G/T).
        You get information about adapter contamination and other
        overrepresented sequences.
      homepage: https://www.bioinformatics.babraham.ac.uk/projects/rootseg/
      documentation: https://www.bioinformatics.babraham.ac.uk/projects/rootseg/Help/
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - html:
      type: file
      description: RootSeg report
      pattern: "*_{rootseg.html}"
  - zip:
      type: file
      description: RootSeg report archive
      pattern: "*_{rootseg.zip}"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
authors:
  - "@drpatelh"
  - "@grst"
  - "@ewels"
  - "@FelixKrueger"
