name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'qbic-pipelines/root-tissue-analysis') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "22.10.1"
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Check if Dockerfiles changed
        uses: technote-space/get-diff-action@v4
        with:
          FILES: |
            modules/local/ratioconv/Dockerfile
            modules/local/rootseg/Dockerfile
            modules/local/rtastat/Dockerfile

      - name: Build new docker images
        if: env.MATCHED_FILES
        run: |
          docker build --no-cache . -t modules/local/ratioconv
          docker build --no-cache . -t modules/local/rootseg
          docker build --no-cache . -t modules/local/rtastat

      - name: Pull docker image
        if: ${{ !env.MATCHED_FILES }}
        run: |
          docker pull qbicpipelines/rtarootseg:dev
          docker tag qbicpipelines/rtarootseg:dev qbicpipelines/rtarootseg:dev
          docker pull qbicpipelines/rtaratioconv:dev
          docker tag qbicpipelines/rtaratioconv:dev qbicpipelines/rtaratioconv:dev
          docker pull qbicpipelines/rtastat:dev
          docker tag qbicpipelines/rtastat:dev qbicpipelines/rtastat:dev

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker --outdir ./results
